CREATE TABLE IF NOT EXISTS employee (
    id_karyawan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_karyawan VARCHAR(120) NOT NULL,
    kode_karyawan VARCHAR(6) NOT NULL UNIQUE,
    tanggal_lahir DATE NOT NULL,
    alamat VARCHAR(240),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS salary (
    id_salary BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulan VARCHAR(10) NOT NULL,
    tahun INTEGER NOT NULL,
    salary NUMERIC(15,2) NOT NULL,
    id_karyawan BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_salary_employee
        FOREIGN KEY (id_karyawan)
        REFERENCES employee(id_karyawan)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT unique_salary_period
        UNIQUE (id_karyawan, bulan, tahun),

    CONSTRAINT salary_positive
        CHECK (salary > 0)
);

CREATE TABLE IF NOT EXISTS bonus (
    id_bonus BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bonus NUMERIC(15,2) NOT NULL,
    total NUMERIC(15,2) NOT NULL,
    id_karyawan BIGINT NOT NULL,
    id_salary BIGINT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),

    CONSTRAINT fk_bonus_employee
        FOREIGN KEY (id_karyawan)
        REFERENCES employee(id_karyawan)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_bonus_salary
        FOREIGN KEY (id_salary)
        REFERENCES salary(id_salary)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT bonus_non_negative
        CHECK (bonus >= 0),

    CONSTRAINT total_non_negative
        CHECK (total >= 0)
);
